### PR TITLE
refactor(io): Improve Path representation and serialization

### PR DESCRIPTION
**Pull request by clementlrd**
- Create a "Expand" Generic type for Path objects that can be used in conjunction with DirectoryPath, FilePath and NewPath from pydantic.types. Example: Expand[DirectoryPath]. This Generic type add a pydantic validator to expand the given path. Then, it is no longer necessary to use field_validator to expand the user/make the path absolute for every path variable (in BaseModel).
- Path serialization is now handled in the io module through manual serialization (json and yaml). it is no longer necessary to specify how to serialize a Path in the BaseModel with the field_serialization decorator.

Summary: Everything should be simpler and clearer in the schema module.

### CODE REVIEW

**Comment by clementlrd** [comment]
Thanks the tests to make me realize my mistake x)

**Comment by clementlrd** [comment]
I don't get what you're talking about when you say the `lazy loading` part seems independent. Are you referring to the part where where I removed the lazy loading for yaml and json in the io module?

To elaborate a bit more on that part, It was easier for me to just remove this lazy loading than trying to also lazily create the encoder for each library (json/yaml). For now, these two libraries have to be fully supported because we use them in our code in different places, and the loading is definitely not a performance overhead, hence my choice. If you want I can still do this lazy creation, but I find it really useful if we want to support other libraries that are not the default and may not be installed.

**Review by toniodo — APPROVED** [review]
It was a bit complicated to understand the lines with `TypeVar` and `Annotated`, but now with the documentation, I think it should be fine! The rest is also fine.

**Comment by clementlrd** [comment]
Great! Indeed `TypeVar` is to create a [generic](https://docs.python.org/3/library/typing.html#generics) type. This will be way simpler in python 3.12 as it is more explicit. With the bound argument, I can specify a scope to the values the generic variable can take, so here it can only be a Path or any subclass. I can then use the type like this: `Expanded[Path]`.

Annotation is for type annotation but as a special meaning when combined with pydantic as it is the recommended method to add validators  to a type. When the given type is used, the validator (here path expansion) will be applied (should works only in a pydantic context).

@Seb-sti1 wait for your reply before merging. I'm for a squash so elaborate on your comment please.

**Comment by toniodo** [comment]
Okay, thank you for the explanations!

**Comment by Seb-sti1** [comment]
For the `lazy loading` I was referring to the `projecthub/io.py` changes but it's actually linked to the rest so, as you said, a squash is preferable :)

**Pull request merged**
